"""empty message

Revision ID: 4d68e1cd1853
Revises: afb3384e0986
Create Date: 2026-01-27 14:56:47.570196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d68e1cd1853'
down_revision: Union[str, Sequence[str], None] = 'afb3384e0986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('ticker', sa.Enum('btc_usd', 'eth_usd', name='typecurrency'), nullable=False))
    op.drop_column('ticker', 'type_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('type_currency', postgresql.ENUM('btc_usd', 'eth_usd', name='typecurrency'), autoincrement=False, nullable=False))
    op.drop_column('ticker', 'ticker')
    # ### end Alembic commands ###
